# Generated by Django 4.2.3 on 2023-08-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0002_alter_task_options_remove_task_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
