# Generated by Django 4.2.3 on 2023-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0003_rename_description_task_task_remove_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
