# Generated by Django 4.2.3 on 2023-08-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0004_rename_task_task_description_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
