# Generated by Django 4.2.3 on 2023-08-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0005_rename_description_task_task_remove_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_due']},
        ),
    ]
