# Generated by Django 4.2.3 on 2023-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
