# Generated by Django 4.2.3 on 2023-08-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0008_rename_task_taskcompletion_task_name_task_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
