# Generated by Django 4.2.3 on 2023-08-17 17:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('ordered_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
