# Generated by Django 4.2.3 on 2023-08-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0010_alter_task_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
